service:
  name: ringcentral-personal-chatbot-1
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 256
  environment: ${file(./env.yml)}
  profile: default
  excludeDevDependencies: true
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: "*"
package:
  include:
    - '*.json'
    - '*.js'
    - 'node_modules/**'
functions:
  maintain:
    tags:
      department: dev
      Owner: zzzz
      Environment: xxxx
      Team: xx
      Name: ringcentral-personal-chatbot-faq
    description: ringcentral-personal-chatbot-faq by Drake.Zhao@ringcentral.com
    # role: arn:aws:iam::xxxx:role/lambda_basic_execution_john.wang
    handler: lambda.maintain
    events:
      - schedule: rate(1 day)
  app:
    handler: lambda.app
    timeout: 400 # 5 miutes
    # role: arn:aws:iam::111111:role/xxxx-prod-us-east-1-lambdaRole
    # vpc:
    #   securityGroupIds:
    #     - sg-xxx
    #     - sg-yyy
    #   subnetIds:
    #     - subnet-ttt
    #     - subnet-ggg
    #     - subnet-vvv
    tags:
      department: dev
      Owner: Your name
      Stage: production
      Environment: your-env-tag
      Team: your-team
      Name: ringcentral-engage-chatbot-1
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
